services:
  gateway:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: uvicorn gateway.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      RUNPOD_ENDPOINT: ${RUNPOD_ENDPOINT:-http://runpod-worker:8000}
      RUNPOD_API_KEY: ${RUNPOD_API_KEY:-}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      LOCAL_STORAGE_ROOT: ${LOCAL_STORAGE_ROOT:-/data/uploads}
      MODEL_VERSION: ${MODEL_VERSION:-qwen2.5-vl-72b}
    volumes:
      - uploads:/data/uploads
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: celery -A gateway.tasks.celery_app worker --loglevel=info
    environment:
      RUNPOD_ENDPOINT: ${RUNPOD_ENDPOINT:-http://runpod-worker:8000}
      RUNPOD_API_KEY: ${RUNPOD_API_KEY:-}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      LOCAL_STORAGE_ROOT: ${LOCAL_STORAGE_ROOT:-/data/uploads}
      MODEL_VERSION: ${MODEL_VERSION:-qwen2.5-vl-72b}
    volumes:
      - uploads:/data/uploads
    depends_on:
      - redis

  runpod-worker:
    profiles: ["local-worker"]
    build:
      context: .
      dockerfile: docker/runpod/Dockerfile
    environment:
      MODEL_VERSION: ${MODEL_VERSION:-qwen2.5-vl-72b}
    ports:
      - "8100:8000"
    volumes:
      - models:/models

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  uploads:
  models:
